package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aula generated by hbm2java
 */
@Entity
@Table(name="AULA"
    ,schema="PROSOCIAL"
)
public class Aula  implements java.io.Serializable {


     private String idaula;
     private Ciclo ciclo;
     private Escuela escuela;
     private BigDecimal numCiclo;
     private BigDecimal numGrupo;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;

    public Aula() {
    }

	
    public Aula(String idaula, Ciclo ciclo, Escuela escuela, BigDecimal numCiclo, BigDecimal numGrupo, String usuarioCre, Date fechaCre) {
        this.idaula = idaula;
        this.ciclo = ciclo;
        this.escuela = escuela;
        this.numCiclo = numCiclo;
        this.numGrupo = numGrupo;
        this.usuarioCre = usuarioCre;
        this.fechaCre = fechaCre;
    }
    public Aula(String idaula, Ciclo ciclo, Escuela escuela, BigDecimal numCiclo, BigDecimal numGrupo, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod) {
       this.idaula = idaula;
       this.ciclo = ciclo;
       this.escuela = escuela;
       this.numCiclo = numCiclo;
       this.numGrupo = numGrupo;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
    }
   
     @Id 

    
    @Column(name="IDAULA", unique=true, nullable=false, length=12)
    public String getIdaula() {
        return this.idaula;
    }
    
    public void setIdaula(String idaula) {
        this.idaula = idaula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCICLO", nullable=false)
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDESCUELA", nullable=false)
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }

    
    @Column(name="NUM_CICLO", nullable=false, precision=22, scale=0)
    public BigDecimal getNumCiclo() {
        return this.numCiclo;
    }
    
    public void setNumCiclo(BigDecimal numCiclo) {
        this.numCiclo = numCiclo;
    }

    
    @Column(name="NUM_GRUPO", nullable=false, precision=22, scale=0)
    public BigDecimal getNumGrupo() {
        return this.numGrupo;
    }
    
    public void setNumGrupo(BigDecimal numGrupo) {
        this.numGrupo = numGrupo;
    }

    
    @Column(name="USUARIO_CRE", nullable=false, length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", nullable=false, length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


