package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetAulaUsuario generated by hbm2java
 */
@Entity
@Table(name="DET_AULA_USUARIO"
    ,schema="PROSOCIAL"
)
public class DetAulaUsuario  implements java.io.Serializable {


     private DetAulaUsuarioId id;
     private Aula aula;
     private Usuario usuario;

    public DetAulaUsuario() {
    }

    public DetAulaUsuario(DetAulaUsuarioId id, Aula aula, Usuario usuario) {
       this.id = id;
       this.aula = aula;
       this.usuario = usuario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idusuario", column=@Column(name="IDUSUARIO", nullable=false, length=12) ), 
        @AttributeOverride(name="idaula", column=@Column(name="IDAULA", nullable=false, length=12) ) } )
    public DetAulaUsuarioId getId() {
        return this.id;
    }
    
    public void setId(DetAulaUsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAULA", nullable=false, insertable=false, updatable=false)
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIO", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


