package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetAulaUsuarioId generated by hbm2java
 */
@Embeddable
public class DetAulaUsuarioId  implements java.io.Serializable {


     private String idusuario;
     private String idaula;

    public DetAulaUsuarioId() {
    }

    public DetAulaUsuarioId(String idusuario, String idaula) {
       this.idusuario = idusuario;
       this.idaula = idaula;
    }
   


    @Column(name="IDUSUARIO", nullable=false, length=12)
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }


    @Column(name="IDAULA", nullable=false, length=12)
    public String getIdaula() {
        return this.idaula;
    }
    
    public void setIdaula(String idaula) {
        this.idaula = idaula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetAulaUsuarioId) ) return false;
		 DetAulaUsuarioId castOther = ( DetAulaUsuarioId ) other; 
         
		 return ( (this.getIdusuario()==castOther.getIdusuario()) || ( this.getIdusuario()!=null && castOther.getIdusuario()!=null && this.getIdusuario().equals(castOther.getIdusuario()) ) )
 && ( (this.getIdaula()==castOther.getIdaula()) || ( this.getIdaula()!=null && castOther.getIdaula()!=null && this.getIdaula().equals(castOther.getIdaula()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdusuario() == null ? 0 : this.getIdusuario().hashCode() );
         result = 37 * result + ( getIdaula() == null ? 0 : this.getIdaula().hashCode() );
         return result;
   }   


}


