package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetPrivilegioLinkId generated by hbm2java
 */
@Embeddable
public class DetPrivilegioLinkId  implements java.io.Serializable {


     private String idlink;
     private String idprivilegio;

    public DetPrivilegioLinkId() {
    }

    public DetPrivilegioLinkId(String idlink, String idprivilegio) {
       this.idlink = idlink;
       this.idprivilegio = idprivilegio;
    }
   


    @Column(name="IDLINK", nullable=false, length=12)
    public String getIdlink() {
        return this.idlink;
    }
    
    public void setIdlink(String idlink) {
        this.idlink = idlink;
    }


    @Column(name="IDPRIVILEGIO", nullable=false, length=12)
    public String getIdprivilegio() {
        return this.idprivilegio;
    }
    
    public void setIdprivilegio(String idprivilegio) {
        this.idprivilegio = idprivilegio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetPrivilegioLinkId) ) return false;
		 DetPrivilegioLinkId castOther = ( DetPrivilegioLinkId ) other; 
         
		 return ( (this.getIdlink()==castOther.getIdlink()) || ( this.getIdlink()!=null && castOther.getIdlink()!=null && this.getIdlink().equals(castOther.getIdlink()) ) )
 && ( (this.getIdprivilegio()==castOther.getIdprivilegio()) || ( this.getIdprivilegio()!=null && castOther.getIdprivilegio()!=null && this.getIdprivilegio().equals(castOther.getIdprivilegio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdlink() == null ? 0 : this.getIdlink().hashCode() );
         result = 37 * result + ( getIdprivilegio() == null ? 0 : this.getIdprivilegio().hashCode() );
         return result;
   }   


}


