package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetRolPrivilegioId generated by hbm2java
 */
@Embeddable
public class DetRolPrivilegioId  implements java.io.Serializable {


     private String idprivilegio;
     private String idrol;

    public DetRolPrivilegioId() {
    }

    public DetRolPrivilegioId(String idprivilegio, String idrol) {
       this.idprivilegio = idprivilegio;
       this.idrol = idrol;
    }
   


    @Column(name="IDPRIVILEGIO", nullable=false, length=12)
    public String getIdprivilegio() {
        return this.idprivilegio;
    }
    
    public void setIdprivilegio(String idprivilegio) {
        this.idprivilegio = idprivilegio;
    }


    @Column(name="IDROL", nullable=false, length=12)
    public String getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(String idrol) {
        this.idrol = idrol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetRolPrivilegioId) ) return false;
		 DetRolPrivilegioId castOther = ( DetRolPrivilegioId ) other; 
         
		 return ( (this.getIdprivilegio()==castOther.getIdprivilegio()) || ( this.getIdprivilegio()!=null && castOther.getIdprivilegio()!=null && this.getIdprivilegio().equals(castOther.getIdprivilegio()) ) )
 && ( (this.getIdrol()==castOther.getIdrol()) || ( this.getIdrol()!=null && castOther.getIdrol()!=null && this.getIdrol().equals(castOther.getIdrol()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdprivilegio() == null ? 0 : this.getIdprivilegio().hashCode() );
         result = 37 * result + ( getIdrol() == null ? 0 : this.getIdrol().hashCode() );
         return result;
   }   


}


