package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetRolPrivilegio generated by hbm2java
 */
@Entity
@Table(name="DET_ROL_PRIVILEGIO"
    ,schema="PROSOCIAL"
)
public class DetRolPrivilegio  implements java.io.Serializable {


     private DetRolPrivilegioId id;
     private Privilegio privilegio;
     private Rol rol;

    public DetRolPrivilegio() {
    }

    public DetRolPrivilegio(DetRolPrivilegioId id, Privilegio privilegio, Rol rol) {
       this.id = id;
       this.privilegio = privilegio;
       this.rol = rol;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idprivilegio", column=@Column(name="IDPRIVILEGIO", nullable=false, length=12) ), 
        @AttributeOverride(name="idrol", column=@Column(name="IDROL", nullable=false, length=12) ) } )
    public DetRolPrivilegioId getId() {
        return this.id;
    }
    
    public void setId(DetRolPrivilegioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPRIVILEGIO", nullable=false, insertable=false, updatable=false)
    public Privilegio getPrivilegio() {
        return this.privilegio;
    }
    
    public void setPrivilegio(Privilegio privilegio) {
        this.privilegio = privilegio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDROL", nullable=false, insertable=false, updatable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


