package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetUsuarioRol generated by hbm2java
 */
@Entity
@Table(name="DET_USUARIO_ROL"
    ,schema="PROSOCIAL"
)
public class DetUsuarioRol  implements java.io.Serializable {


     private DetUsuarioRolId id;
     private Rol rol;
     private Usuario usuario;

    public DetUsuarioRol() {
    }

    public DetUsuarioRol(DetUsuarioRolId id, Rol rol, Usuario usuario) {
       this.id = id;
       this.rol = rol;
       this.usuario = usuario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idrol", column=@Column(name="IDROL", nullable=false, length=12) ), 
        @AttributeOverride(name="idusuario", column=@Column(name="IDUSUARIO", nullable=false, length=12) ) } )
    public DetUsuarioRolId getId() {
        return this.id;
    }
    
    public void setId(DetUsuarioRolId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDROL", nullable=false, insertable=false, updatable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDUSUARIO", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


