package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escuela generated by hbm2java
 */
@Entity
@Table(name="ESCUELA"
    ,schema="PROSOCIAL"
)
public class Escuela  implements java.io.Serializable {


     private String idescuela;
     private Facultad facultad;
     private String nombreEs;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;
     private Set aulas = new HashSet(0);

    public Escuela() {
    }

	
    public Escuela(String idescuela, Facultad facultad) {
        this.idescuela = idescuela;
        this.facultad = facultad;
    }
    public Escuela(String idescuela, Facultad facultad, String nombreEs, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod, Set aulas) {
       this.idescuela = idescuela;
       this.facultad = facultad;
       this.nombreEs = nombreEs;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
       this.aulas = aulas;
    }
   
     @Id 

    
    @Column(name="IDESCUELA", unique=true, nullable=false, length=12)
    public String getIdescuela() {
        return this.idescuela;
    }
    
    public void setIdescuela(String idescuela) {
        this.idescuela = idescuela;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFACULTAD", nullable=false)
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    
    @Column(name="NOMBRE_ES", length=45)
    public String getNombreEs() {
        return this.nombreEs;
    }
    
    public void setNombreEs(String nombreEs) {
        this.nombreEs = nombreEs;
    }

    
    @Column(name="USUARIO_CRE", length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="escuela")
    public Set getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set aulas) {
        this.aulas = aulas;
    }




}


