package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Escuela generated by hbm2java
 */
@Entity
@Table(name="ESCUELA"
    ,schema="PROSOCIAL"
)
public class Escuela  implements java.io.Serializable {


     private String idescuela;
     private Facultad facultad;
     private String nombreEs;
     private Set aulas = new HashSet(0);

    public Escuela() {
    }

	
    public Escuela(String idescuela, Facultad facultad) {
        this.idescuela = idescuela;
        this.facultad = facultad;
    }
    public Escuela(String idescuela, Facultad facultad, String nombreEs, Set aulas) {
       this.idescuela = idescuela;
       this.facultad = facultad;
       this.nombreEs = nombreEs;
       this.aulas = aulas;
    }
   
     @Id 

    
    @Column(name="IDESCUELA", unique=true, nullable=false, length=12)
    public String getIdescuela() {
        return this.idescuela;
    }
    
    public void setIdescuela(String idescuela) {
        this.idescuela = idescuela;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFACULTAD", nullable=false)
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    
    @Column(name="NOMBRE_ES", length=45)
    public String getNombreEs() {
        return this.nombreEs;
    }
    
    public void setNombreEs(String nombreEs) {
        this.nombreEs = nombreEs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="escuela")
    public Set getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Set aulas) {
        this.aulas = aulas;
    }




}


