package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name="EVENTO"
    ,schema="PROSOCIAL"
)
public class Evento  implements java.io.Serializable {


     private String idevento;
     private Proyecto proyecto;
     private TipoEvento tipoEvento;
     private String nombreEv;
     private Date fechaEv;
     private String lugarEv;
     private char estadoEv;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;
     private Set inscripcions = new HashSet(0);
     private Set archivos = new HashSet(0);
     private Set asistencias = new HashSet(0);

    public Evento() {
    }

	
    public Evento(String idevento, Proyecto proyecto, TipoEvento tipoEvento, String nombreEv, char estadoEv, String usuarioCre, Date fechaCre) {
        this.idevento = idevento;
        this.proyecto = proyecto;
        this.tipoEvento = tipoEvento;
        this.nombreEv = nombreEv;
        this.estadoEv = estadoEv;
        this.usuarioCre = usuarioCre;
        this.fechaCre = fechaCre;
    }
    public Evento(String idevento, Proyecto proyecto, TipoEvento tipoEvento, String nombreEv, Date fechaEv, String lugarEv, char estadoEv, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod, Set inscripcions, Set archivos, Set asistencias) {
       this.idevento = idevento;
       this.proyecto = proyecto;
       this.tipoEvento = tipoEvento;
       this.nombreEv = nombreEv;
       this.fechaEv = fechaEv;
       this.lugarEv = lugarEv;
       this.estadoEv = estadoEv;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
       this.inscripcions = inscripcions;
       this.archivos = archivos;
       this.asistencias = asistencias;
    }
   
     @Id 

    
    @Column(name="IDEVENTO", unique=true, nullable=false, length=12)
    public String getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(String idevento) {
        this.idevento = idevento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDPROYECTO", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIPO_EVENTO", nullable=false)
    public TipoEvento getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(TipoEvento tipoEvento) {
        this.tipoEvento = tipoEvento;
    }

    
    @Column(name="NOMBRE_EV", nullable=false, length=30)
    public String getNombreEv() {
        return this.nombreEv;
    }
    
    public void setNombreEv(String nombreEv) {
        this.nombreEv = nombreEv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_EV", length=7)
    public Date getFechaEv() {
        return this.fechaEv;
    }
    
    public void setFechaEv(Date fechaEv) {
        this.fechaEv = fechaEv;
    }

    
    @Column(name="LUGAR_EV", length=20)
    public String getLugarEv() {
        return this.lugarEv;
    }
    
    public void setLugarEv(String lugarEv) {
        this.lugarEv = lugarEv;
    }

    
    @Column(name="ESTADO_EV", nullable=false, length=1)
    public char getEstadoEv() {
        return this.estadoEv;
    }
    
    public void setEstadoEv(char estadoEv) {
        this.estadoEv = estadoEv;
    }

    
    @Column(name="USUARIO_CRE", nullable=false, length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", nullable=false, length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set archivos) {
        this.archivos = archivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


