package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name="FACULTAD"
    ,schema="PROSOCIAL"
)
public class Facultad  implements java.io.Serializable {


     private String idfacultad;
     private String nombreFa;
     private String nombreCortoFa;
     private Set escuelas = new HashSet(0);
     private Set proyectos = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(String idfacultad) {
        this.idfacultad = idfacultad;
    }
    public Facultad(String idfacultad, String nombreFa, String nombreCortoFa, Set escuelas, Set proyectos) {
       this.idfacultad = idfacultad;
       this.nombreFa = nombreFa;
       this.nombreCortoFa = nombreCortoFa;
       this.escuelas = escuelas;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="IDFACULTAD", unique=true, nullable=false, length=12)
    public String getIdfacultad() {
        return this.idfacultad;
    }
    
    public void setIdfacultad(String idfacultad) {
        this.idfacultad = idfacultad;
    }

    
    @Column(name="NOMBRE_FA", length=45)
    public String getNombreFa() {
        return this.nombreFa;
    }
    
    public void setNombreFa(String nombreFa) {
        this.nombreFa = nombreFa;
    }

    
    @Column(name="NOMBRE_CORTO_FA", length=10)
    public String getNombreCortoFa() {
        return this.nombreCortoFa;
    }
    
    public void setNombreCortoFa(String nombreCortoFa) {
        this.nombreCortoFa = nombreCortoFa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facultad")
    public Set getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set escuelas) {
        this.escuelas = escuelas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facultad")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }




}


