package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name="FACULTAD"
    ,schema="PROSOCIAL"
)
public class Facultad  implements java.io.Serializable {


     private String idfacultad;
     private String nombreFa;
     private String nombreCortoFa;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;
     private Set escuelas = new HashSet(0);
     private Set proyectos = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(String idfacultad) {
        this.idfacultad = idfacultad;
    }
    public Facultad(String idfacultad, String nombreFa, String nombreCortoFa, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod, Set escuelas, Set proyectos) {
       this.idfacultad = idfacultad;
       this.nombreFa = nombreFa;
       this.nombreCortoFa = nombreCortoFa;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
       this.escuelas = escuelas;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="IDFACULTAD", unique=true, nullable=false, length=12)
    public String getIdfacultad() {
        return this.idfacultad;
    }
    
    public void setIdfacultad(String idfacultad) {
        this.idfacultad = idfacultad;
    }

    
    @Column(name="NOMBRE_FA", length=45)
    public String getNombreFa() {
        return this.nombreFa;
    }
    
    public void setNombreFa(String nombreFa) {
        this.nombreFa = nombreFa;
    }

    
    @Column(name="NOMBRE_CORTO_FA", length=10)
    public String getNombreCortoFa() {
        return this.nombreCortoFa;
    }
    
    public void setNombreCortoFa(String nombreCortoFa) {
        this.nombreCortoFa = nombreCortoFa;
    }

    
    @Column(name="USUARIO_CRE", length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facultad")
    public Set getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set escuelas) {
        this.escuelas = escuelas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="facultad")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }




}


