package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name = "LINK", schema = "PROSOCIAL"
)
public class Link implements java.io.Serializable {

    private String idlink;
    private String nombreLink;
    private String iconoLink;
    private BigDecimal NOrden;
    private String link;
    private Set detPrivilegioLinks = new HashSet(0);

    public Link() {
    }

    public Link(String idlink) {
        this.idlink = idlink;
    }

    public Link(String idlink, String nombreLink, String iconoLink, BigDecimal NOrden, String link, Set detPrivilegioLinks) {
        this.idlink = idlink;
        this.nombreLink = nombreLink;
        this.iconoLink = iconoLink;
        this.NOrden = NOrden;
        this.detPrivilegioLinks = detPrivilegioLinks;
        this.link = link;
    }

    @Id

    @Column(name = "IDLINK", unique = true, nullable = false, length = 12)
    public String getIdlink() {
        return this.idlink;
    }

    public void setIdlink(String idlink) {
        this.idlink = idlink;
    }

    @Column(name = "NOMBRE_LINK")
    public String getNombreLink() {
        return this.nombreLink;
    }

    public void setNombreLink(String nombreLink) {
        this.nombreLink = nombreLink;
    }

    @Column(name = "ICONO_LINK", length = 25)
    public String getIconoLink() {
        return this.iconoLink;
    }

    public void setIconoLink(String iconoLink) {
        this.iconoLink = iconoLink;
    }

    @Column(name = "N_ORDEN", precision = 22, scale = 0)
    public BigDecimal getNOrden() {
        return this.NOrden;
    }

    public void setNOrden(BigDecimal NOrden) {
        this.NOrden = NOrden;
    }

    @Column(name = "LINK", precision = 255)
    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "link")
    public Set getDetPrivilegioLinks() {
        return this.detPrivilegioLinks;
    }

    public void setDetPrivilegioLinks(Set detPrivilegioLinks) {
        this.detPrivilegioLinks = detPrivilegioLinks;
    }

}
