package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="LINK"
    ,schema="PROSOCIAL"
)
public class Link  implements java.io.Serializable {


     private String idlink;
     private String nombreLink;
     private String iconoLink;
     private BigDecimal NOrden;
     private String link;
     private Character tipoLink;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;

    public Link() {
    }

	
    public Link(String idlink, String nombreLink, String link) {
        this.idlink = idlink;
        this.nombreLink = nombreLink;
        this.link = link;
    }
    public Link(String idlink, String nombreLink, String iconoLink, BigDecimal NOrden, String link, Character tipoLink, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod) {
       this.idlink = idlink;
       this.nombreLink = nombreLink;
       this.iconoLink = iconoLink;
       this.NOrden = NOrden;
       this.link = link;
       this.tipoLink = tipoLink;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
    }
   
     @Id 

    
    @Column(name="IDLINK", unique=true, nullable=false, length=12)
    public String getIdlink() {
        return this.idlink;
    }
    
    public void setIdlink(String idlink) {
        this.idlink = idlink;
    }

    
    @Column(name="NOMBRE_LINK", nullable=false, length=35)
    public String getNombreLink() {
        return this.nombreLink;
    }
    
    public void setNombreLink(String nombreLink) {
        this.nombreLink = nombreLink;
    }

    
    @Column(name="ICONO_LINK", length=65)
    public String getIconoLink() {
        return this.iconoLink;
    }
    
    public void setIconoLink(String iconoLink) {
        this.iconoLink = iconoLink;
    }

    
    @Column(name="N_ORDEN", precision=22, scale=0)
    public BigDecimal getNOrden() {
        return this.NOrden;
    }
    
    public void setNOrden(BigDecimal NOrden) {
        this.NOrden = NOrden;
    }

    
    @Column(name="LINK", nullable=false)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="TIPO_LINK", length=1)
    public Character getTipoLink() {
        return this.tipoLink;
    }
    
    public void setTipoLink(Character tipoLink) {
        this.tipoLink = tipoLink;
    }

    
    @Column(name="USUARIO_CRE", length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


