package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificacion generated by hbm2java
 */
@Entity
@Table(name="NOTIFICACION"
    ,schema="PROSOCIAL"
)
public class Notificacion  implements java.io.Serializable {


     private String idnotificacion;
     private String idusuario;
     private String titulo;
     private String contenido;
     private String icono;
     private Date fecha;
     private Character tipo;
     private Character estado;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;

    public Notificacion() {
    }

	
    public Notificacion(String idnotificacion) {
        this.idnotificacion = idnotificacion;
    }
    public Notificacion(String idnotificacion, String idusuario, String titulo, String contenido, String icono, Date fecha, Character tipo, Character estado, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod) {
       this.idnotificacion = idnotificacion;
       this.idusuario = idusuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.icono = icono;
       this.fecha = fecha;
       this.tipo = tipo;
       this.estado = estado;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
    }
   
     @Id 

    
    @Column(name="IDNOTIFICACION", unique=true, nullable=false, length=12)
    public String getIdnotificacion() {
        return this.idnotificacion;
    }
    
    public void setIdnotificacion(String idnotificacion) {
        this.idnotificacion = idnotificacion;
    }

    
    @Column(name="IDUSUARIO", length=12)
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="TITULO", length=35)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="CONTENIDO")
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    
    @Column(name="ICONO", length=35)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="TIPO", length=1)
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="ESTADO", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }

    
    @Column(name="USUARIO_CRE", length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


