package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="PROYECTO"
    ,schema="PROSOCIAL"
)
public class Proyecto  implements java.io.Serializable {


     private String idproyecto;
     private Facultad facultad;
     private String nombrePy;
     private String descripcionPy;
     private String comentarioPy;
     private char estadoPy;
     private String idarchivoPy;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;
     private Set eventos = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(String idproyecto, Facultad facultad, String nombrePy, char estadoPy, String usuarioCre, Date fechaCre) {
        this.idproyecto = idproyecto;
        this.facultad = facultad;
        this.nombrePy = nombrePy;
        this.estadoPy = estadoPy;
        this.usuarioCre = usuarioCre;
        this.fechaCre = fechaCre;
    }
    public Proyecto(String idproyecto, Facultad facultad, String nombrePy, String descripcionPy, String comentarioPy, char estadoPy, String idarchivoPy, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod, Set eventos) {
       this.idproyecto = idproyecto;
       this.facultad = facultad;
       this.nombrePy = nombrePy;
       this.descripcionPy = descripcionPy;
       this.comentarioPy = comentarioPy;
       this.estadoPy = estadoPy;
       this.idarchivoPy = idarchivoPy;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
       this.eventos = eventos;
    }
   
     @Id 

    
    @Column(name="IDPROYECTO", unique=true, nullable=false, length=12)
    public String getIdproyecto() {
        return this.idproyecto;
    }
    
    public void setIdproyecto(String idproyecto) {
        this.idproyecto = idproyecto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFACULTAD", nullable=false)
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    
    @Column(name="NOMBRE_PY", nullable=false, length=60)
    public String getNombrePy() {
        return this.nombrePy;
    }
    
    public void setNombrePy(String nombrePy) {
        this.nombrePy = nombrePy;
    }

    
    @Column(name="DESCRIPCION_PY")
    public String getDescripcionPy() {
        return this.descripcionPy;
    }
    
    public void setDescripcionPy(String descripcionPy) {
        this.descripcionPy = descripcionPy;
    }

    
    @Column(name="COMENTARIO_PY")
    public String getComentarioPy() {
        return this.comentarioPy;
    }
    
    public void setComentarioPy(String comentarioPy) {
        this.comentarioPy = comentarioPy;
    }

    
    @Column(name="ESTADO_PY", nullable=false, length=1)
    public char getEstadoPy() {
        return this.estadoPy;
    }
    
    public void setEstadoPy(char estadoPy) {
        this.estadoPy = estadoPy;
    }

    
    @Column(name="IDARCHIVO_PY", length=12)
    public String getIdarchivoPy() {
        return this.idarchivoPy;
    }
    
    public void setIdarchivoPy(String idarchivoPy) {
        this.idarchivoPy = idarchivoPy;
    }

    
    @Column(name="USUARIO_CRE", nullable=false, length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", nullable=false, length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


