package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="ROL"
    ,schema="PROSOCIAL"
)
public class Rol  implements java.io.Serializable {


     private String idrol;
     private String nombreRo;
     private char estadoRo;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;

    public Rol() {
    }

	
    public Rol(String idrol, String nombreRo, char estadoRo, String usuarioCre, Date fechaCre) {
        this.idrol = idrol;
        this.nombreRo = nombreRo;
        this.estadoRo = estadoRo;
        this.usuarioCre = usuarioCre;
        this.fechaCre = fechaCre;
    }
    public Rol(String idrol, String nombreRo, char estadoRo, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod) {
       this.idrol = idrol;
       this.nombreRo = nombreRo;
       this.estadoRo = estadoRo;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
    }
   
     @Id 

    
    @Column(name="IDROL", unique=true, nullable=false, length=12)
    public String getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(String idrol) {
        this.idrol = idrol;
    }

    
    @Column(name="NOMBRE_RO", nullable=false, length=35)
    public String getNombreRo() {
        return this.nombreRo;
    }
    
    public void setNombreRo(String nombreRo) {
        this.nombreRo = nombreRo;
    }

    
    @Column(name="ESTADO_RO", nullable=false, length=1)
    public char getEstadoRo() {
        return this.estadoRo;
    }
    
    public void setEstadoRo(char estadoRo) {
        this.estadoRo = estadoRo;
    }

    
    @Column(name="USUARIO_CRE", nullable=false, length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", nullable=false, length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }




}


