package com.ps.entidad;
// Generated 17/03/2016 11:27:41 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoEvento generated by hbm2java
 */
@Entity
@Table(name="TIPO_EVENTO"
    ,schema="PROSOCIAL"
)
public class TipoEvento  implements java.io.Serializable {


     private String idtipoEvento;
     private String nombreTie;
     private String usuarioCre;
     private String usuarioMod;
     private Date fechaCre;
     private Date fechaMod;
     private Set eventos = new HashSet(0);

    public TipoEvento() {
    }

	
    public TipoEvento(String idtipoEvento) {
        this.idtipoEvento = idtipoEvento;
    }
    public TipoEvento(String idtipoEvento, String nombreTie, String usuarioCre, String usuarioMod, Date fechaCre, Date fechaMod, Set eventos) {
       this.idtipoEvento = idtipoEvento;
       this.nombreTie = nombreTie;
       this.usuarioCre = usuarioCre;
       this.usuarioMod = usuarioMod;
       this.fechaCre = fechaCre;
       this.fechaMod = fechaMod;
       this.eventos = eventos;
    }
   
     @Id 

    
    @Column(name="IDTIPO_EVENTO", unique=true, nullable=false, length=12)
    public String getIdtipoEvento() {
        return this.idtipoEvento;
    }
    
    public void setIdtipoEvento(String idtipoEvento) {
        this.idtipoEvento = idtipoEvento;
    }

    
    @Column(name="NOMBRE_TIE", length=25)
    public String getNombreTie() {
        return this.nombreTie;
    }
    
    public void setNombreTie(String nombreTie) {
        this.nombreTie = nombreTie;
    }

    
    @Column(name="USUARIO_CRE", length=12)
    public String getUsuarioCre() {
        return this.usuarioCre;
    }
    
    public void setUsuarioCre(String usuarioCre) {
        this.usuarioCre = usuarioCre;
    }

    
    @Column(name="USUARIO_MOD", length=12)
    public String getUsuarioMod() {
        return this.usuarioMod;
    }
    
    public void setUsuarioMod(String usuarioMod) {
        this.usuarioMod = usuarioMod;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CRE", length=7)
    public Date getFechaCre() {
        return this.fechaCre;
    }
    
    public void setFechaCre(Date fechaCre) {
        this.fechaCre = fechaCre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MOD", length=7)
    public Date getFechaMod() {
        return this.fechaMod;
    }
    
    public void setFechaMod(Date fechaMod) {
        this.fechaMod = fechaMod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEvento")
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


