package com.ps.entidad;
// Generated 01/07/2015 06:18:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEvento generated by hbm2java
 */
@Entity
@Table(name="TIPO_EVENTO"
    ,schema="PROSOCIAL"
)
public class TipoEvento  implements java.io.Serializable {


     private String idtipoEvento;
     private String nombreTie;
     private Set eventos = new HashSet(0);

    public TipoEvento() {
    }

	
    public TipoEvento(String idtipoEvento) {
        this.idtipoEvento = idtipoEvento;
    }
    public TipoEvento(String idtipoEvento, String nombreTie, Set eventos) {
       this.idtipoEvento = idtipoEvento;
       this.nombreTie = nombreTie;
       this.eventos = eventos;
    }
   
     @Id 

    
    @Column(name="IDTIPO_EVENTO", unique=true, nullable=false, length=12)
    public String getIdtipoEvento() {
        return this.idtipoEvento;
    }
    
    public void setIdtipoEvento(String idtipoEvento) {
        this.idtipoEvento = idtipoEvento;
    }

    
    @Column(name="NOMBRE_TIE", length=25)
    public String getNombreTie() {
        return this.nombreTie;
    }
    
    public void setNombreTie(String nombreTie) {
        this.nombreTie = nombreTie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEvento")
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


